apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}-hdfs-http
  labels:
    app: hdfs-namenode
spec:
  ports:
    - port: {{ .Values.namenode.webPort }}
      protocol: TCP
      targetPort: {{ .Values.namenode.webPort }}
      nodePort: {{ .Values.namenode.nodePort }}
  type: NodePort
  selector:
    github.dataworkbench.com/statefulset-name: {{ .Release.Name }}-namenode
{{- if .Values.yarn.nmReplicas }}
---
apiVersion: v1
kind: Service
metadata:
  name: my-yarn-ui
  labels:
    component: yarn-ui
spec:
  ports:
    - port: 8088
      name: web
      nodePort: 30088
  type: NodePort
  selector:
    github.dataworkbench.com/statefulset-name: {{ .Release.Name }}-yarn-rm
{{- end }}